spring:
    application:
      name: gateway
    session:
      store-type: redis
    cloud: 
      gateway: 
        routes: 
          - id: user
            uri: lb://user
            predicates: 
             - Path= /user/**
            filters:
             - StripPrefix= 1
##Redis configuartion
      redis:
         namespace: session
         flush-mose: on-save
    redis: 
       host: localhost
       port: 6379
eureka:
    client:
      service:
         defaultZone: http://localhost:8761/eureka/
      instance:
         preferIpAddress:true

server:
   port:8099